# Generated by Django 4.2.6 on 2023-11-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del Modelo')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre del Modelo')),
                ('año', models.IntegerField(blank=True, null=True, verbose_name='Año del Modelo')),
                ('carroceria', models.IntegerField(blank=True, choices=[(1, 'Sedan'), (2, 'Hatchback'), (3, 'Station Wagon'), (4, 'Pickup'), (5, 'SUV'), (6, 'Van'), (7, 'Convertible'), (8, 'Coupe'), (9, 'Roadster'), (10, 'Camion'), (11, 'Camioneta'), (12, 'Bus'), (13, 'Minivan'), (14, 'Microbus'), (15, 'Micro'), (16, 'Tracto Camion'), (17, 'Trailer')], max_length=30, null=True, verbose_name='Carrocería')),
                ('cilindraje', models.IntegerField(blank=True, null=True, verbose_name='Cilindraje')),
                ('potencia', models.IntegerField(blank=True, null=True, verbose_name='Potencia')),
                ('combustible', models.IntegerField(blank=True, choices=[(1, 'Gasolina'), (2, 'Diesel'), (3, 'Electrico'), (4, 'Hibrido'), (5, 'Gas'), (6, 'Gas Natural'), (7, 'Gas Licuado')], max_length=2, null=True, verbose_name='Combustible')),
                ('numeroPasajeros', models.IntegerField(blank=True, null=True, verbose_name='Número de Pasajeros')),
                ('precioBase', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Base')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'ordering': ['nombre'],
            },
        ),
    ]
