# Generated by Django 4.2.6 on 2023-11-04 22:07

import concesionarioapp.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cedula', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Cédula')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('primer_nombre', models.CharField(max_length=30, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(max_length=30, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Apellido')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono')),
                ('celular', models.CharField(blank=True, max_length=10, null=True, verbose_name='Celular')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ciudad')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], null=True, verbose_name='Género')),
                ('is_active', models.BooleanField(default=True, verbose_name='Usuario activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Usuario parte del staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Usuario es superusuario')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['primer_apellido', 'primer_nombre'],
            },
            managers=[
                ('objects', concesionarioapp.managers.AdministradorUsuarios()),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del Modelo')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre del Modelo')),
                ('año', models.IntegerField(blank=True, null=True, verbose_name='Año del Modelo')),
                ('carroceria', models.IntegerField(blank=True, choices=[(1, 'Sedan'), (2, 'Hatchback'), (3, 'Station Wagon'), (4, 'Pickup'), (5, 'SUV'), (6, 'Van'), (7, 'Convertible'), (8, 'Coupe'), (9, 'Roadster'), (10, 'Camion'), (11, 'Camioneta'), (12, 'Bus'), (13, 'Minivan'), (14, 'Microbus'), (15, 'Micro'), (16, 'Tracto Camion'), (17, 'Trailer')], max_length=30, null=True, verbose_name='Carrocería')),
                ('cilindraje', models.IntegerField(blank=True, null=True, verbose_name='Cilindraje')),
                ('potencia', models.IntegerField(blank=True, null=True, verbose_name='Potencia')),
                ('combustible', models.IntegerField(blank=True, choices=[(1, 'Gasolina'), (2, 'Diesel'), (3, 'Electrico'), (4, 'Hibrido'), (5, 'Gas'), (6, 'Gas Natural'), (7, 'Gas Licuado')], max_length=2, null=True, verbose_name='Combustible')),
                ('numeroPasajeros', models.IntegerField(blank=True, null=True, verbose_name='Número de Pasajeros')),
                ('precioBase', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Base')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la Sucursal')),
                ('nombre_sucursal', models.CharField(max_length=30, unique=True, verbose_name='Nombre de la Sucursal')),
                ('direccion_sucursal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección de la Sucursal')),
                ('ciudad_sucursal', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ciudad de la Sucursal')),
                ('telefono_sucursal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono de la Sucursal')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre_sucursal'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['usuario__primer_apellido', 'usuario__primer_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('fecha_retiro', models.DateField(blank=True, null=True, verbose_name='Fecha de Retiro')),
                ('salario_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario')),
                ('tipo_sangre', models.CharField(blank=True, max_length=3, null=True, verbose_name='Tipo de Sangre')),
                ('eps', models.CharField(blank=True, max_length=30, null=True, verbose_name='EPS')),
                ('arl', models.CharField(blank=True, max_length=30, null=True, verbose_name='ARL')),
                ('cargo', models.CharField(choices=[('A', 'Administrador'), ('V', 'Vendedor'), ('J', 'Jefe de taller')], max_length=1, verbose_name='Cargo')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='concesionarioapp.sucursal')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['usuario__primer_apellido', 'usuario__primer_nombre'],
            },
        ),
    ]
