# Generated by Django 4.2.6 on 2023-11-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionarioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='nombre_modelo',
            field=models.CharField(max_length=30, verbose_name='Nombre del Modelo'),
        ),
    ]
