# Generated by Django 4.2.6 on 2023-12-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionarioapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='porcentanje_incremento_por_color',
            new_name='porcentaje_incremento_por_color',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='porcentaje_descuento',
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_creacion',
            field=models.DateField(verbose_name='Fecha de Creación'),
        ),
    ]
