# Generated by Django 4.2.6 on 2023-12-06 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionarioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2023, 12, 26), verbose_name='Fecha de Vencimiento'),
        ),
    ]
